default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        verbose: true

  - repo: meta
    hooks:
      - id: check-hooks-apply
        verbose: true
      - id: check-useless-excludes
        verbose: true
      - id: identity
        verbose: true

  - repo: local
    hooks:
      - id: chatgpt-commit-message
        name: ChatGPT commit message
        entry: python -m chatgpt_pre_commit_hooks.main
        language: python
        language_version: python3
        additional_dependencies: ["openai>=0.27.4", "tiktoken>=0.3.3"]
        args:
          - "--hook"
          - "chatgpt-commit-message"
          - "--log-level"
          - "debug"
          - "--env-prefix"
          - "work"
          - "--max-char-count"
          - "500"
          - "--emoji"
          - "--description"
        stages: [prepare-commit-msg]
        verbose: true

  # - repo: https://github.com/commit-check/commit-check
  #   rev: v0.5.6
  #   hooks:
  #     - id: check-message
  #       verbose: true
  #     - id: check-branch
  #     - id: check-author-name
  #     - id: check-author-email
