repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
      - id: identity

  - repo: local
    hooks:
      - id: chatgpt-commit-message
        name: Run chatgpt-commit-message
        entry: chatgpt_pre_commit_hooks/chatgpt_commit_message.py
        language: python
        additional_dependencies:
          ["openai>=0.27.4", "tiktoken>=0.3.3", "GitPython>=3.1.31"]
        args:
          - "--env-prefix"
          - "personal"
          - "--max-char-count"
          - "500"
          - "--emoji"
          - "--description"
        stages: [prepare-commit-msg]
