---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
    paths:
      - "*.py"
      - "docs/**"
      - "hooks/**"
      - "chatgpt_pre_commit_hooks/**"
      - ".pre-commit-config.yaml"
      - ".pre-commit-hooks.yaml"
      - "pyproject.toml"

# Allow one concurrent
concurrency:
  group: ${{ format('{0}-{1}', github.event_name, github.ref) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gh-diag:
    name: Run GitHub diagnostic
    uses: ./.github/workflows/reuse.ghdiag.yml

  dependency-review:
    if: ${{ github.repository_visibility == 'public' && (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true

  codeql-analyze:
    if: ${{ github.repository_visibility == 'public' && (github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft && !contains(github.event.head_commit.message, 'skip-codeql'))) }}
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Use only 'java' to analyze code written in Java, Kotlin or both
        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: security-extended
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality

      # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      #   If the Autobuild fails above, remove it and uncomment the following three lines.
      #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

      # - run: |
      #     echo "Run, Build Application using script"
      #     ./location_of_script_within_repo/buildscript.sh

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
          upload: false
          output: codeql-results

      - name: Upload Sarif Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Analyses Results (SARIF)
          path: codeql-results
          if-no-files-found: warn

  codeql-results:
    if: ${{ github.repository_visibility == 'public' && (github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft && !contains(github.event.head_commit.message, 'skip-codeql'))) }}
    name: CodeQL Results
    needs:
      - codeql-analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Sarifs
        uses: actions/download-artifact@v3
        with:
          path: codeql-results

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql-results
          wait-for-processing: true

  lint:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: pip install .[dev]

      - name: Run Ruff
        run: ruff check --config pyproject.toml --no-fix .

  test-build:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    name: Test (build)
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install . .[dev]

      - name: Test Build
        run: python -m build --wheel
